export interface MenuItem {
  name: string
  price: number
  description: string
  isVeg: boolean
  isBestseller?: boolean
}

export interface Restaurant {
  id: string
  name: string
  city: string
  cuisine: string[]
  rating: number
  deliveryTime: string
  priceForTwo: number
  image: string
  isPromoted?: boolean
  discount?: string
  menuItems: MenuItem[]
}

export const cities = ["All Cities", "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai"]

export const cuisineFilters = [
  "All",
  "North Indian",
  "South Indian",
  "Chinese",
  "Italian",
  "Mexican",
  "Japanese",
  "Continental",
  "Biryani",
  "Pizza",
  "Cafe",
]

export const restaurants: Restaurant[] = [
  // Mumbai Restaurants
  {
    id: "1",
    name: "Spice Garden",
    city: "Mumbai",
    cuisine: ["North Indian", "Mughlai"],
    rating: 4.5,
    deliveryTime: "25-30 min",
    priceForTwo: 600,
    image: "/elegant-indian-restaurant-interior-with-warm-light.jpg",
    isPromoted: true,
    discount: "50% OFF up to ₹100",
    menuItems: [
      {
        name: "Butter Chicken",
        price: 320,
        description: "Creamy tomato-based curry with tender chicken",
        isVeg: false,
        isBestseller: true,
      },
      {
        name: "Dal Makhani",
        price: 240,
        description: "Slow-cooked black lentils in rich gravy",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Garlic Naan", price: 60, description: "Soft bread with garlic and butter", isVeg: true },
      { name: "Paneer Tikka", price: 280, description: "Grilled cottage cheese with spices", isVeg: true },
    ],
  },
  {
    id: "2",
    name: "The Wok House",
    city: "Mumbai",
    cuisine: ["Chinese", "Thai"],
    rating: 4.3,
    deliveryTime: "30-35 min",
    priceForTwo: 550,
    image: "/modern-asian-restaurant-with-bamboo-decor.jpg",
    discount: "20% OFF",
    menuItems: [
      {
        name: "Hakka Noodles",
        price: 220,
        description: "Stir-fried noodles with vegetables",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Chilli Chicken", price: 290, description: "Spicy Indo-Chinese chicken", isVeg: false },
      { name: "Veg Manchurian", price: 200, description: "Crispy vegetable balls in tangy sauce", isVeg: true },
      { name: "Spring Rolls", price: 180, description: "Crispy rolls with vegetable filling", isVeg: true },
    ],
  },
  {
    id: "3",
    name: "Pizza Paradise",
    city: "Mumbai",
    cuisine: ["Italian", "Pizza"],
    rating: 4.6,
    deliveryTime: "20-25 min",
    priceForTwo: 500,
    image: "/cozy-italian-pizzeria-with-wood-fired-oven.jpg",
    isPromoted: true,
    menuItems: [
      {
        name: "Margherita Pizza",
        price: 299,
        description: "Classic tomato, mozzarella, and basil",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Pepperoni Pizza", price: 399, description: "Loaded with spicy pepperoni", isVeg: false },
      { name: "Garlic Bread", price: 149, description: "Crispy bread with garlic butter", isVeg: true },
      { name: "Pasta Alfredo", price: 279, description: "Creamy white sauce pasta", isVeg: true },
    ],
  },
  {
    id: "4",
    name: "Coastal Flavors",
    city: "Mumbai",
    cuisine: ["South Indian", "Seafood"],
    rating: 4.4,
    deliveryTime: "35-40 min",
    priceForTwo: 700,
    image: "/coastal-seafood-restaurant-with-ocean-view.jpg",
    menuItems: [
      { name: "Fish Curry", price: 380, description: "Authentic Goan fish curry", isVeg: false, isBestseller: true },
      { name: "Prawn Fry", price: 420, description: "Crispy fried prawns with masala", isVeg: false },
      { name: "Appam", price: 80, description: "Soft rice pancakes", isVeg: true },
      { name: "Coconut Rice", price: 120, description: "Fragrant rice with coconut", isVeg: true },
    ],
  },
  {
    id: "5",
    name: "Brew & Bites",
    city: "Mumbai",
    cuisine: ["Cafe", "Continental"],
    rating: 4.2,
    deliveryTime: "15-20 min",
    priceForTwo: 400,
    image: "/trendy-coffee-shop-with-exposed-brick-walls.jpg",
    discount: "Free Delivery",
    menuItems: [
      {
        name: "Cappuccino",
        price: 180,
        description: "Rich espresso with frothy milk",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Club Sandwich", price: 220, description: "Triple-decker with chicken and veggies", isVeg: false },
      { name: "Chocolate Brownie", price: 150, description: "Warm fudgy brownie", isVeg: true },
      { name: "Caesar Salad", price: 250, description: "Fresh romaine with creamy dressing", isVeg: true },
    ],
  },
  {
    id: "6",
    name: "Tandoor Tales",
    city: "Mumbai",
    cuisine: ["North Indian", "Biryani"],
    rating: 4.7,
    deliveryTime: "40-45 min",
    priceForTwo: 800,
    image: "/luxurious-indian-restaurant-with-chandelier.jpg",
    isPromoted: true,
    discount: "₹150 OFF above ₹499",
    menuItems: [
      {
        name: "Lucknowi Biryani",
        price: 350,
        description: "Aromatic dum biryani with tender meat",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Seekh Kebab", price: 280, description: "Minced meat skewers from tandoor", isVeg: false },
      { name: "Veg Biryani", price: 250, description: "Fragrant rice with mixed vegetables", isVeg: true },
      { name: "Raita", price: 60, description: "Cooling yogurt side", isVeg: true },
    ],
  },
  {
    id: "7",
    name: "Sushi Station",
    city: "Mumbai",
    cuisine: ["Japanese", "Sushi"],
    rating: 4.5,
    deliveryTime: "30-35 min",
    priceForTwo: 1200,
    image: "/minimalist-japanese-sushi-bar.jpg",
    menuItems: [
      {
        name: "California Roll",
        price: 450,
        description: "Crab, avocado, and cucumber roll",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Salmon Nigiri", price: 380, description: "Fresh salmon over seasoned rice", isVeg: false },
      { name: "Edamame", price: 180, description: "Steamed soybeans with sea salt", isVeg: true },
      { name: "Miso Soup", price: 150, description: "Traditional Japanese soup", isVeg: true },
    ],
  },
  {
    id: "8",
    name: "Taco Loco",
    city: "Mumbai",
    cuisine: ["Mexican", "Tex-Mex"],
    rating: 4.3,
    deliveryTime: "25-30 min",
    priceForTwo: 600,
    image: "/vibrant-mexican-restaurant-with-colorful-decor.jpg",
    discount: "Buy 2 Get 1 Free",
    menuItems: [
      {
        name: "Chicken Tacos",
        price: 280,
        description: "Soft tacos with grilled chicken",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Burrito Bowl", price: 320, description: "Rice bowl with beans and salsa", isVeg: true },
      { name: "Nachos Supreme", price: 250, description: "Loaded nachos with cheese and jalapeños", isVeg: true },
      { name: "Churros", price: 180, description: "Crispy pastry with chocolate dip", isVeg: true },
    ],
  },
  {
    id: "9",
    name: "Green Leaf",
    city: "Mumbai",
    cuisine: ["Cafe", "Healthy"],
    rating: 4.4,
    deliveryTime: "20-25 min",
    priceForTwo: 450,
    image: "/modern-healthy-cafe-with-plants.jpg",
    menuItems: [
      {
        name: "Acai Bowl",
        price: 350,
        description: "Superfood bowl with fresh fruits",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Avocado Toast", price: 280, description: "Multigrain toast with fresh avocado", isVeg: true },
      { name: "Green Smoothie", price: 220, description: "Spinach, banana, and almond milk", isVeg: true },
      { name: "Quinoa Salad", price: 320, description: "Protein-rich grain salad", isVeg: true },
    ],
  },
  {
    id: "10",
    name: "Royal Kitchen",
    city: "Mumbai",
    cuisine: ["North Indian", "Mughlai"],
    rating: 4.8,
    deliveryTime: "35-40 min",
    priceForTwo: 900,
    image: "/royal-indian-dining-with-traditional-decor.jpg",
    isPromoted: true,
    menuItems: [
      {
        name: "Mutton Rogan Josh",
        price: 450,
        description: "Kashmiri style mutton curry",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Shahi Paneer", price: 320, description: "Rich creamy paneer curry", isVeg: true },
      { name: "Laccha Paratha", price: 60, description: "Layered flaky bread", isVeg: true },
      { name: "Gulab Jamun", price: 120, description: "Soft milk dumplings in syrup", isVeg: true },
    ],
  },
  // Delhi Restaurants
  {
    id: "11",
    name: "Delhi Darbar",
    city: "Delhi",
    cuisine: ["North Indian", "Mughlai"],
    rating: 4.6,
    deliveryTime: "30-35 min",
    priceForTwo: 700,
    image: "/grand-delhi-restaurant-with-mughal-architecture.jpg",
    isPromoted: true,
    discount: "40% OFF up to ₹80",
    menuItems: [
      {
        name: "Chole Bhature",
        price: 180,
        description: "Spiced chickpeas with fried bread",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Butter Naan", price: 50, description: "Soft buttered flatbread", isVeg: true },
      { name: "Kadai Paneer", price: 280, description: "Paneer in spicy bell pepper gravy", isVeg: true },
      { name: "Chicken Tikka", price: 320, description: "Smoky tandoor-grilled chicken", isVeg: false },
    ],
  },
  {
    id: "12",
    name: "Chandni Chowk Delights",
    city: "Delhi",
    cuisine: ["Street Food", "North Indian"],
    rating: 4.4,
    deliveryTime: "25-30 min",
    priceForTwo: 350,
    image: "/colorful-indian-street-food-stall.jpg",
    discount: "₹50 OFF",
    menuItems: [
      { name: "Paranthe", price: 120, description: "Stuffed flatbreads with pickle", isVeg: true, isBestseller: true },
      { name: "Aloo Tikki", price: 80, description: "Crispy potato patties with chutney", isVeg: true },
      { name: "Dahi Bhalla", price: 100, description: "Lentil dumplings in yogurt", isVeg: true },
      { name: "Jalebi", price: 60, description: "Crispy sweet spirals", isVeg: true },
    ],
  },
  {
    id: "13",
    name: "The Dragon Wok",
    city: "Delhi",
    cuisine: ["Chinese", "Pan Asian"],
    rating: 4.3,
    deliveryTime: "35-40 min",
    priceForTwo: 600,
    image: "/elegant-chinese-restaurant-with-red-lanterns.jpg",
    menuItems: [
      {
        name: "Kung Pao Chicken",
        price: 320,
        description: "Spicy stir-fried chicken with peanuts",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Dim Sum Platter", price: 380, description: "Assorted steamed dumplings", isVeg: false },
      { name: "Fried Rice", price: 220, description: "Wok-tossed rice with vegetables", isVeg: true },
      { name: "Hot & Sour Soup", price: 150, description: "Tangy spicy soup", isVeg: true },
    ],
  },
  {
    id: "14",
    name: "Italiano Express",
    city: "Delhi",
    cuisine: ["Italian", "Pizza"],
    rating: 4.5,
    deliveryTime: "20-25 min",
    priceForTwo: 550,
    image: "/rustic-italian-trattoria.jpg",
    isPromoted: true,
    menuItems: [
      {
        name: "Truffle Pasta",
        price: 450,
        description: "Creamy pasta with truffle oil",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Quattro Formaggi", price: 420, description: "Four cheese pizza", isVeg: true },
      { name: "Bruschetta", price: 180, description: "Toasted bread with tomato topping", isVeg: true },
      { name: "Tiramisu", price: 280, description: "Classic Italian dessert", isVeg: true },
    ],
  },
  {
    id: "15",
    name: "Biryani Blues",
    city: "Delhi",
    cuisine: ["Biryani", "Hyderabadi"],
    rating: 4.7,
    deliveryTime: "40-45 min",
    priceForTwo: 650,
    image: "/traditional-biryani-pot-restaurant.jpg",
    discount: "Free Biryani on orders above ₹599",
    menuItems: [
      {
        name: "Hyderabadi Chicken Biryani",
        price: 320,
        description: "Authentic dum-cooked biryani",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Mutton Biryani", price: 380, description: "Rich mutton layered rice", isVeg: false },
      { name: "Paneer Biryani", price: 280, description: "Vegetarian aromatic biryani", isVeg: true },
      { name: "Double Ka Meetha", price: 150, description: "Traditional bread pudding", isVeg: true },
    ],
  },
  {
    id: "16",
    name: "South Express",
    city: "Delhi",
    cuisine: ["South Indian"],
    rating: 4.2,
    deliveryTime: "25-30 min",
    priceForTwo: 300,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        name: "Masala Dosa",
        price: 120,
        description: "Crispy rice crepe with potato filling",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Idli Sambar", price: 80, description: "Steamed rice cakes with lentil soup", isVeg: true },
      { name: "Vada", price: 60, description: "Crispy lentil fritters", isVeg: true },
      { name: "Filter Coffee", price: 50, description: "Traditional South Indian coffee", isVeg: true },
    ],
  },
  {
    id: "17",
    name: "Kebab Factory",
    city: "Delhi",
    cuisine: ["North Indian", "Kebabs"],
    rating: 4.6,
    deliveryTime: "35-40 min",
    priceForTwo: 850,
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      {
        name: "Galouti Kebab",
        price: 380,
        description: "Melt-in-mouth minced meat kebabs",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Kakori Kebab", price: 350, description: "Silky smooth seekh kebabs", isVeg: false },
      { name: "Paneer Tikka", price: 280, description: "Marinated cottage cheese", isVeg: true },
      { name: "Roomali Roti", price: 40, description: "Paper-thin bread", isVeg: true },
    ],
  },
  {
    id: "18",
    name: "The Coffee House",
    city: "Delhi",
    cuisine: ["Cafe", "Bakery"],
    rating: 4.4,
    deliveryTime: "15-20 min",
    priceForTwo: 450,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Cold Brew", price: 200, description: "Smooth cold-steeped coffee", isVeg: true, isBestseller: true },
      { name: "Croissant", price: 150, description: "Buttery French pastry", isVeg: true },
      { name: "Cheese Sandwich", price: 180, description: "Grilled cheese on sourdough", isVeg: true },
      { name: "Cheesecake", price: 280, description: "New York style cheesecake", isVeg: true },
    ],
  },
  {
    id: "19",
    name: "Wok This Way",
    city: "Delhi",
    cuisine: ["Chinese", "Thai"],
    rating: 4.1,
    deliveryTime: "30-35 min",
    priceForTwo: 500,
    image: "/placeholder.svg?height=200&width=300",
    discount: "30% OFF",
    menuItems: [
      {
        name: "Thai Green Curry",
        price: 320,
        description: "Coconut curry with vegetables",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Pad Thai", price: 280, description: "Stir-fried rice noodles", isVeg: true },
      { name: "Tom Yum Soup", price: 180, description: "Spicy Thai soup", isVeg: true },
      { name: "Mango Sticky Rice", price: 200, description: "Sweet Thai dessert", isVeg: true },
    ],
  },
  {
    id: "20",
    name: "Punjab Grill",
    city: "Delhi",
    cuisine: ["North Indian", "Punjabi"],
    rating: 4.8,
    deliveryTime: "40-45 min",
    priceForTwo: 950,
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      {
        name: "Sarson Da Saag",
        price: 320,
        description: "Mustard greens with makki roti",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Amritsari Fish", price: 420, description: "Crispy battered fish fry", isVeg: false },
      { name: "Lassi", price: 120, description: "Thick creamy yogurt drink", isVeg: true },
      { name: "Phirni", price: 150, description: "Traditional rice pudding", isVeg: true },
    ],
  },
  // Bangalore Restaurants
  {
    id: "21",
    name: "MTR Heritage",
    city: "Bangalore",
    cuisine: ["South Indian"],
    rating: 4.7,
    deliveryTime: "25-30 min",
    priceForTwo: 400,
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      {
        name: "Rava Idli",
        price: 100,
        description: "Semolina idlis with special sambar",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Benne Dosa", price: 120, description: "Butter dosa Bangalore style", isVeg: true },
      { name: "Kesari Bath", price: 80, description: "Sweet semolina pudding", isVeg: true },
      { name: "Filter Coffee", price: 60, description: "Strong South Indian coffee", isVeg: true },
    ],
  },
  {
    id: "22",
    name: "Empire Restaurant",
    city: "Bangalore",
    cuisine: ["Biryani", "North Indian"],
    rating: 4.5,
    deliveryTime: "35-40 min",
    priceForTwo: 550,
    image: "/placeholder.svg?height=200&width=300",
    discount: "20% OFF on Biryani",
    menuItems: [
      { name: "Empire Biryani", price: 280, description: "Signature spicy biryani", isVeg: false, isBestseller: true },
      { name: "Shawarma", price: 150, description: "Middle Eastern wrap", isVeg: false },
      { name: "Kebab Platter", price: 380, description: "Assorted grilled kebabs", isVeg: false },
      { name: "Phirni", price: 100, description: "Creamy rice pudding", isVeg: true },
    ],
  },
  {
    id: "23",
    name: "Truffles",
    city: "Bangalore",
    cuisine: ["Continental", "American"],
    rating: 4.6,
    deliveryTime: "30-35 min",
    priceForTwo: 600,
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      { name: "Truffle Burger", price: 350, description: "Signature juicy burger", isVeg: false, isBestseller: true },
      { name: "Cheese Fries", price: 180, description: "Loaded cheese french fries", isVeg: true },
      { name: "BBQ Wings", price: 280, description: "Smoky barbecue chicken wings", isVeg: false },
      { name: "Brownie Sundae", price: 220, description: "Warm brownie with ice cream", isVeg: true },
    ],
  },
  {
    id: "24",
    name: "Vidyarthi Bhavan",
    city: "Bangalore",
    cuisine: ["South Indian"],
    rating: 4.4,
    deliveryTime: "20-25 min",
    priceForTwo: 250,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        name: "Masala Dosa",
        price: 90,
        description: "Crispy dosa with potato masala",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Khara Bath", price: 70, description: "Savory semolina dish", isVeg: true },
      { name: "Vada", price: 50, description: "Crispy lentil donuts", isVeg: true },
      { name: "Coffee", price: 40, description: "Traditional filter coffee", isVeg: true },
    ],
  },
  {
    id: "25",
    name: "Toit Brewpub",
    city: "Bangalore",
    cuisine: ["Continental", "Cafe"],
    rating: 4.5,
    deliveryTime: "40-45 min",
    priceForTwo: 1200,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        name: "Wood Fired Pizza",
        price: 450,
        description: "Artisan pizza from brick oven",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Fish & Chips", price: 380, description: "Beer-battered fish with fries", isVeg: false },
      { name: "Nachos Grande", price: 320, description: "Loaded nachos with toppings", isVeg: true },
      { name: "Craft Beer", price: 350, description: "House-brewed beer", isVeg: true },
    ],
  },
  {
    id: "26",
    name: "Meghana Foods",
    city: "Bangalore",
    cuisine: ["Andhra", "Biryani"],
    rating: 4.6,
    deliveryTime: "30-35 min",
    priceForTwo: 500,
    image: "/placeholder.svg?height=200&width=300",
    discount: "Free Dessert",
    menuItems: [
      {
        name: "Andhra Chicken Biryani",
        price: 280,
        description: "Spicy Andhra style biryani",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Chicken 65", price: 250, description: "Crispy spicy chicken", isVeg: false },
      { name: "Meals", price: 200, description: "Traditional thali", isVeg: true },
      { name: "Gulab Jamun", price: 80, description: "Sweet milk dumplings", isVeg: true },
    ],
  },
  {
    id: "27",
    name: "Corner House",
    city: "Bangalore",
    cuisine: ["Desserts", "Ice Cream"],
    rating: 4.8,
    deliveryTime: "15-20 min",
    priceForTwo: 350,
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      {
        name: "Death By Chocolate",
        price: 220,
        description: "Ultimate chocolate dessert",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Hot Chocolate Fudge", price: 180, description: "Ice cream with hot fudge", isVeg: true },
      { name: "Sundae", price: 150, description: "Classic ice cream sundae", isVeg: true },
      { name: "Milkshake", price: 120, description: "Thick creamy shake", isVeg: true },
    ],
  },
  {
    id: "28",
    name: "Udupi Grand",
    city: "Bangalore",
    cuisine: ["South Indian", "Udupi"],
    rating: 4.3,
    deliveryTime: "25-30 min",
    priceForTwo: 300,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Set Dosa", price: 100, description: "Soft fluffy dosas", isVeg: true, isBestseller: true },
      { name: "Bisibele Bath", price: 120, description: "Spicy rice with lentils", isVeg: true },
      { name: "Paddu", price: 80, description: "Crispy rice balls", isVeg: true },
      { name: "Payasam", price: 70, description: "Sweet vermicelli pudding", isVeg: true },
    ],
  },
  {
    id: "29",
    name: "Byg Brewski",
    city: "Bangalore",
    cuisine: ["Continental", "Indian"],
    rating: 4.4,
    deliveryTime: "45-50 min",
    priceForTwo: 1500,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        name: "Butter Garlic Prawns",
        price: 550,
        description: "Succulent prawns in butter",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Mushroom Pizza", price: 420, description: "Wild mushroom thin crust", isVeg: true },
      { name: "Pasta Arrabiata", price: 350, description: "Spicy tomato pasta", isVeg: true },
      { name: "Tiramisu", price: 280, description: "Italian coffee dessert", isVeg: true },
    ],
  },
  {
    id: "30",
    name: "Shivaji Military Hotel",
    city: "Bangalore",
    cuisine: ["North Karnataka", "Non-Veg"],
    rating: 4.5,
    deliveryTime: "35-40 min",
    priceForTwo: 450,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        name: "Mutton Dry Fry",
        price: 320,
        description: "Spicy dry mutton preparation",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Ragi Mudde", price: 50, description: "Finger millet balls", isVeg: true },
      { name: "Jolada Roti", price: 30, description: "Sorghum flatbread", isVeg: true },
      { name: "Chicken Saaru", price: 200, description: "Spicy chicken curry", isVeg: false },
    ],
  },
  // Hyderabad Restaurants
  {
    id: "31",
    name: "Paradise Biryani",
    city: "Hyderabad",
    cuisine: ["Biryani", "Hyderabadi"],
    rating: 4.7,
    deliveryTime: "35-40 min",
    priceForTwo: 600,
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    discount: "₹100 OFF above ₹399",
    menuItems: [
      {
        name: "Paradise Special Biryani",
        price: 350,
        description: "Legendary Hyderabadi biryani",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Chicken 65", price: 280, description: "Spicy fried chicken", isVeg: false },
      { name: "Mirchi Ka Salan", price: 180, description: "Chili in peanut gravy", isVeg: true },
      { name: "Qubani Ka Meetha", price: 150, description: "Apricot dessert", isVeg: true },
    ],
  },
  {
    id: "32",
    name: "Shah Ghouse",
    city: "Hyderabad",
    cuisine: ["Biryani", "Haleem"],
    rating: 4.5,
    deliveryTime: "40-45 min",
    priceForTwo: 550,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Mutton Biryani", price: 380, description: "Old city style biryani", isVeg: false, isBestseller: true },
      { name: "Haleem", price: 250, description: "Slow-cooked meat porridge", isVeg: false },
      { name: "Paya", price: 220, description: "Goat trotters curry", isVeg: false },
      { name: "Sheer Khurma", price: 120, description: "Festive vermicelli dessert", isVeg: true },
    ],
  },
  {
    id: "33",
    name: "Chutneys",
    city: "Hyderabad",
    cuisine: ["South Indian"],
    rating: 4.4,
    deliveryTime: "25-30 min",
    priceForTwo: 400,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Paper Roast", price: 140, description: "Extra crispy thin dosa", isVeg: true, isBestseller: true },
      { name: "Pesarattu", price: 100, description: "Green gram dosa", isVeg: true },
      { name: "Upma Pesarattu", price: 120, description: "Pesarattu with upma filling", isVeg: true },
      { name: "Pongal", price: 90, description: "Rice and lentil porridge", isVeg: true },
    ],
  },
  {
    id: "34",
    name: "Pista House",
    city: "Hyderabad",
    cuisine: ["Hyderabadi", "Sweets"],
    rating: 4.6,
    deliveryTime: "30-35 min",
    priceForTwo: 500,
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      { name: "Haleem", price: 280, description: "Award-winning haleem", isVeg: false, isBestseller: true },
      { name: "Double Ka Meetha", price: 150, description: "Bread pudding", isVeg: true },
      { name: "Irani Chai", price: 50, description: "Traditional Hyderabadi tea", isVeg: true },
      { name: "Osmania Biscuit", price: 80, description: "Signature crispy biscuits", isVeg: true },
    ],
  },
  {
    id: "35",
    name: "Bawarchi",
    city: "Hyderabad",
    cuisine: ["Biryani", "North Indian"],
    rating: 4.3,
    deliveryTime: "35-40 min",
    priceForTwo: 480,
    image: "/placeholder.svg?height=200&width=300",
    discount: "20% OFF",
    menuItems: [
      { name: "Special Biryani", price: 300, description: "House special biryani", isVeg: false, isBestseller: true },
      { name: "Tandoori Chicken", price: 350, description: "Whole tandoor roasted chicken", isVeg: false },
      { name: "Paneer Butter Masala", price: 250, description: "Creamy paneer curry", isVeg: true },
      { name: "Kheer", price: 100, description: "Rice pudding", isVeg: true },
    ],
  },
  {
    id: "36",
    name: "Ohri's",
    city: "Hyderabad",
    cuisine: ["Continental", "Indian"],
    rating: 4.5,
    deliveryTime: "40-45 min",
    priceForTwo: 800,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Grilled Fish", price: 450, description: "Fresh fish with herbs", isVeg: false, isBestseller: true },
      { name: "Hyderabadi Dum Biryani", price: 380, description: "Royal style biryani", isVeg: false },
      { name: "Paneer Tikka", price: 280, description: "Grilled cottage cheese", isVeg: true },
      { name: "Chocolate Lava Cake", price: 250, description: "Molten chocolate dessert", isVeg: true },
    ],
  },
  {
    id: "37",
    name: "Karachi Bakery",
    city: "Hyderabad",
    cuisine: ["Bakery", "Cafe"],
    rating: 4.4,
    deliveryTime: "20-25 min",
    priceForTwo: 300,
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      {
        name: "Fruit Biscuits",
        price: 350,
        description: "Signature mixed fruit biscuits",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Osmania Biscuit", price: 200, description: "Classic tea-time biscuits", isVeg: true },
      { name: "Plum Cake", price: 450, description: "Rich fruit cake", isVeg: true },
      { name: "Dilkush", price: 40, description: "Sweet puff pastry", isVeg: true },
    ],
  },
  {
    id: "38",
    name: "Lucky Restaurant",
    city: "Hyderabad",
    cuisine: ["Biryani", "Mughlai"],
    rating: 4.2,
    deliveryTime: "35-40 min",
    priceForTwo: 450,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        name: "Chicken Biryani",
        price: 260,
        description: "Flavorful chicken biryani",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Mutton Fry", price: 320, description: "Spicy mutton dry fry", isVeg: false },
      { name: "Chicken Manchurian", price: 250, description: "Indo-Chinese preparation", isVeg: false },
      { name: "Raita", price: 60, description: "Cool yogurt side", isVeg: true },
    ],
  },
  {
    id: "39",
    name: "Cafe Niloufer",
    city: "Hyderabad",
    cuisine: ["Cafe", "Bakery"],
    rating: 4.6,
    deliveryTime: "15-20 min",
    priceForTwo: 200,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Irani Chai", price: 40, description: "Famous Irani chai", isVeg: true, isBestseller: true },
      { name: "Osmania Biscuit", price: 60, description: "Perfect with chai", isVeg: true },
      { name: "Bun Maska", price: 50, description: "Buttered bun", isVeg: true },
      { name: "Kheema Samosa", price: 80, description: "Minced meat samosa", isVeg: false },
    ],
  },
  {
    id: "40",
    name: "Cream Stone",
    city: "Hyderabad",
    cuisine: ["Desserts", "Ice Cream"],
    rating: 4.5,
    deliveryTime: "20-25 min",
    priceForTwo: 400,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        name: "Stone Mixed Ice Cream",
        price: 280,
        description: "Custom mixed on cold stone",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Brownie Delight", price: 220, description: "Ice cream with warm brownie", isVeg: true },
      { name: "Waffle Tower", price: 300, description: "Belgian waffle with toppings", isVeg: true },
      { name: "Thick Shake", price: 180, description: "Creamy milkshake", isVeg: true },
    ],
  },
  // Chennai Restaurants
  {
    id: "41",
    name: "Saravana Bhavan",
    city: "Chennai",
    cuisine: ["South Indian"],
    rating: 4.6,
    deliveryTime: "25-30 min",
    priceForTwo: 350,
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      { name: "Ghee Roast Dosa", price: 120, description: "Crispy dosa with ghee", isVeg: true, isBestseller: true },
      { name: "Mini Tiffin", price: 180, description: "Assorted South Indian breakfast", isVeg: true },
      { name: "Sambar Rice", price: 100, description: "Rice with lentil curry", isVeg: true },
      { name: "Kesari", price: 60, description: "Sweet semolina dessert", isVeg: true },
    ],
  },
  {
    id: "42",
    name: "Murugan Idli Shop",
    city: "Chennai",
    cuisine: ["South Indian"],
    rating: 4.5,
    deliveryTime: "20-25 min",
    priceForTwo: 250,
    image: "/placeholder.svg?height=200&width=300",
    discount: "₹50 OFF",
    menuItems: [
      {
        name: "Idli with Ghee",
        price: 80,
        description: "Soft idlis drizzled with ghee",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Podi Dosa", price: 100, description: "Dosa with spice powder", isVeg: true },
      { name: "Pongal", price: 90, description: "Creamy rice-lentil dish", isVeg: true },
      { name: "Vada", price: 50, description: "Crispy lentil fritters", isVeg: true },
    ],
  },
  {
    id: "43",
    name: "Ponnusamy Hotel",
    city: "Chennai",
    cuisine: ["Chettinad", "South Indian"],
    rating: 4.4,
    deliveryTime: "35-40 min",
    priceForTwo: 600,
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      { name: "Chettinad Chicken", price: 350, description: "Spicy Chettinad curry", isVeg: false, isBestseller: true },
      { name: "Mutton Chukka", price: 380, description: "Dry mutton preparation", isVeg: false },
      { name: "Parotta", price: 30, description: "Layered flatbread", isVeg: true },
      { name: "Rasam", price: 50, description: "Tangy pepper soup", isVeg: true },
    ],
  },
  {
    id: "44",
    name: "Amethyst",
    city: "Chennai",
    cuisine: ["Continental", "Cafe"],
    rating: 4.5,
    deliveryTime: "40-45 min",
    priceForTwo: 900,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Eggs Benedict", price: 380, description: "Classic brunch dish", isVeg: false, isBestseller: true },
      { name: "Avocado Salad", price: 320, description: "Fresh garden salad", isVeg: true },
      { name: "Pasta Primavera", price: 350, description: "Vegetable pasta", isVeg: true },
      { name: "Carrot Cake", price: 280, description: "Moist spiced cake", isVeg: true },
    ],
  },
  {
    id: "45",
    name: "Junior Kuppanna",
    city: "Chennai",
    cuisine: ["Andhra", "South Indian"],
    rating: 4.3,
    deliveryTime: "30-35 min",
    priceForTwo: 500,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Nattu Kozhi", price: 420, description: "Country chicken curry", isVeg: false, isBestseller: true },
      { name: "Mutton Pepper Fry", price: 380, description: "Spicy pepper mutton", isVeg: false },
      { name: "Chicken Biryani", price: 280, description: "Andhra style biryani", isVeg: false },
      { name: "Payasam", price: 80, description: "Sweet milk pudding", isVeg: true },
    ],
  },
  {
    id: "46",
    name: "Mathsya",
    city: "Chennai",
    cuisine: ["Seafood", "Coastal"],
    rating: 4.6,
    deliveryTime: "35-40 min",
    priceForTwo: 800,
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      { name: "Lobster Thermidor", price: 1200, description: "French-style lobster", isVeg: false, isBestseller: true },
      { name: "Prawn Masala", price: 450, description: "Spicy prawn curry", isVeg: false },
      { name: "Fish Fry", price: 350, description: "Crispy fried fish", isVeg: false },
      { name: "Crab Soup", price: 280, description: "Creamy crab soup", isVeg: false },
    ],
  },
  {
    id: "47",
    name: "Dindigul Thalappakatti",
    city: "Chennai",
    cuisine: ["Biryani", "South Indian"],
    rating: 4.5,
    deliveryTime: "35-40 min",
    priceForTwo: 550,
    image: "/placeholder.svg?height=200&width=300",
    discount: "Free Raita",
    menuItems: [
      {
        name: "Thalappakatti Biryani",
        price: 320,
        description: "Signature seeraga samba biryani",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Mutton Chops", price: 380, description: "Grilled mutton chops", isVeg: false },
      { name: "Chicken Fry", price: 280, description: "Crispy fried chicken", isVeg: false },
      { name: "Badam Milk", price: 80, description: "Almond milk", isVeg: true },
    ],
  },
  {
    id: "48",
    name: "Copper Chimney",
    city: "Chennai",
    cuisine: ["North Indian", "Mughlai"],
    rating: 4.4,
    deliveryTime: "40-45 min",
    priceForTwo: 750,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Dal Bukhara", price: 350, description: "Slow-cooked black lentils", isVeg: true, isBestseller: true },
      { name: "Butter Chicken", price: 380, description: "Creamy tomato chicken", isVeg: false },
      { name: "Naan Basket", price: 180, description: "Assorted breads", isVeg: true },
      { name: "Kulfi", price: 150, description: "Indian ice cream", isVeg: true },
    ],
  },
  {
    id: "49",
    name: "Cream Centre",
    city: "Chennai",
    cuisine: ["Chinese", "Continental"],
    rating: 4.2,
    deliveryTime: "30-35 min",
    priceForTwo: 500,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Paneer Manchurian", price: 280, description: "Indo-Chinese paneer", isVeg: true, isBestseller: true },
      { name: "Sizzler", price: 420, description: "Mixed vegetable sizzler", isVeg: true },
      { name: "Noodles", price: 220, description: "Stir-fried noodles", isVeg: true },
      { name: "Ice Cream Sundae", price: 180, description: "Mixed sundae", isVeg: true },
    ],
  },
  {
    id: "50",
    name: "Sangeetha",
    city: "Chennai",
    cuisine: ["South Indian"],
    rating: 4.3,
    deliveryTime: "20-25 min",
    priceForTwo: 300,
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Thali Meals", price: 180, description: "Complete South Indian thali", isVeg: true, isBestseller: true },
      { name: "Masala Dosa", price: 100, description: "Crispy dosa with filling", isVeg: true },
      { name: "Uttapam", price: 90, description: "Thick rice pancake", isVeg: true },
      { name: "Filter Coffee", price: 40, description: "Strong Chennai filter coffee", isVeg: true },
    ],
  },
]
